<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Reservas\PainelDLX\Domain\Quartos\Entities\Quarto;
use Reservas\PainelDLX\Domain\Reservas\Entities\Reserva;
use Vilex\VileX;

/**
 * @var VileX $this
 */

$lista_reservas = $this->getAtributo('lista-reservas');
$filtro = $this->getAtributo('filtro');
?>
[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<nav class="menu-opcoes">
    <form id="filtro-registros" class="filtro-reservas">
        <div class="filtro-registros">
            <div class="multi-select">
                <span class="multi-select-item">Procurar em...</span>

                <div class="multi-select-itens">
                    <!-- label class="multi-select-item">
                        <input type="checkbox" name="campos[]" value="quarto_nome"<?php echo empty($filtro['campos']) || in_array('quarto_nome', $filtro['campos']) ? ' checked' : '' ?>>
                        Quarto
                    </label -->

                    <label class="multi-select-item">
                        <input type="checkbox" name="campos[]"
                               value="hospede"<?php echo empty($filtro['campos']) || in_array('hospede', $filtro['campos']) ? ' checked' : '' ?>>
                        Hóspede
                    </label>

                    <label class="multi-select-item">
                        <input type="checkbox" name="campos[]"
                               value="status"<?php echo empty($filtro['campos']) || in_array('status', $filtro['campos']) ? ' checked' : '' ?>>
                        Status
                    </label>
                </div>
            </div>

            <input type="search" name="busca" value="<?php echo $filtro['busca'] ?>" placeholder="Encontrar reservas" class="form-controle">
        </div>

        <input type="date" name="data_inicial" id="data-inicial" value="<?php echo $filtro['data_inicial'] ?>" class="form-controle form-controle-data">
        <input type="date" name="data_final" id="data-final" value="<?php echo $filtro['data_final'] ?>" class="form-controle form-controle-data">
    </form>

    <button type="submit" form="filtro-registros" class="botao-buscar">Buscar</button>
    <a href="/painel-dlx/apart-hotel/reservas/reservar-quarto" class="link-inserir">Reservar um quarto</a>
</nav>

<table id="lista-reservas" class="lista-registros">
    <thead>
    <tr>
        <th id="reserva-id">ID</th>
        <th id="quarto">Quarto</th>
        <th id="hospede">Hóspede</th>
        <th id="periodo">Período</th>
        <th id="status">Status</th>
        <th id="opcoes">Opções</th>
    </tr>
    </thead>

    <tbody>
    <?php if (!count($lista_reservas)) : ?>
        <tr>
            <td colspan="6" class="sem-registros">Nenhuma reserva encontrada.</td>
        </tr>
    <?php endif;

    /** @var Reserva $reserva */
    foreach ($lista_reservas as $reserva) : ?>
        <tr>
            <td headers="reserva-id"><?php echo $reserva->getId() ?></td>
            <td headers="quarto"><?php echo $reserva->getQuarto()->getNome() ?></td>
            <td headers="hospede"><?php echo $reserva->getHospede() ?></td>
            <td headers="periodo">
                <?php echo 'De ', $reserva->getCheckin()->format('d/m/Y'),
                    ' até ', $reserva->getCheckout()->format('d/m/Y') ?>

            </td>
            <td headers="status">
                <span class="status-reserva -<?php echo strtolower($reserva->getStatus()) ?>">
                    <?php echo $reserva->getStatus() ?>
                </span>
            </td>
            <td headers="opcoes">
                <a href="/painel-dlx/apart-hotel/reservas/detalhe?id=<?php echo $reserva->getId() ?>" class="link-detalhe" title="Detalhes da reserva">
                    Detalhe
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
[/CORPO]