<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Reservas\Domain\Reservas\Entities\Reserva;
use Vilex\Templates\AbstractTemplate;

/**
 * @var AbstractTemplate $this
 */

/** @var Reserva|null $reserva */
$reserva = $this->getAtributo('reserva');
?>
[CORPO]
<h1 class="titulo-pagina">{{ titulo-pagina }}</h1>

<form id="form-cancelar-reserva" action="/painel-dlx/apart-hotel/reservas/cancelar-reserva" method="post">
    <input type="hidden" name="id" value="<?php echo $reserva->getId() ?>">

    <p class="mensagem-usuario -atencao">
        ATENÇÃO! Essa ação não pode ser defeita.<br>
        Deseja realmente cancelar essa reserva?
    </p>

    <p class="form-paragr">
        <label for="txt-motivo" class="form-rotulo">Motivo:</label>
        <textarea name="motivo" id="txt-motivo" class="form-controle form-controle-textarea" required></textarea>
    </p>

    <p class="form-botoes">
        <button type="button" class="botao-salvar">Não quero cancelar a reserva</button>
        <button type="submit" class="botao-cancelar" data-ajax-msg="Cancelando essa reserva.<br>Por favor aguarde...">
            Sim, desejo cancelar a reserva
        </button>
    </p>
</form>
[/CORPO]