<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Reservas\PainelDLX\Domain\Entities\Pedido;
use Vilex\VileX;

/**
 * @var VileX $this
 */

$lista_pedidos = $this->getAtributo('lista-pedidos');
$filtro = $this->getAtributo('filtro');
?>
[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<nav class="menu-opcoes">
    <form id="filtro-registros" class="filtro-registros">
        <div class="multi-select">
            <span class="multi-select-item">Procurar em...</span>

            <div class="multi-select-itens">
                <label class="multi-select-item">
                    <input type="checkbox" name="campos[]" value="nome"<?php echo empty($filtro['campos']) || in_array('nome', $filtro['campos']) ? ' checked' : '' ?>>
                    Cliente
                </label>

                <label class="multi-select-item">
                    <input type="checkbox" name="campos[]" value="cpf"<?php echo empty($filtro['campos']) || in_array('cpf', $filtro['campos']) ? ' checked' : '' ?>>
                    CPF
                </label>

                <label class="multi-select-item">
                    <input type="checkbox" name="campos[]" value="email"<?php echo empty($filtro['campos']) || in_array('email', $filtro['campos']) ? ' checked' : '' ?>>
                    Email
                </label>
            </div>
        </div>

        <input type="search" name="busca" value="<?php echo $filtro['busca'] ?>" placeholder="Encontrar pedidos" class="form-controle">
    </form>

    <button type="submit" form="filtro-registros" class="botao-buscar">Buscar</button>
</nav>

<table id="lista-quartos" class="lista-registros">
    <thead>
    <tr>
        <th id="pedido-id">ID</th>
        <th id="cliente">Cliente</th>
        <th id="itens" style="text-align: center">Qtde Itens</th>
        <th id="valor">Valor</th>
        <th id="status">Status</th>
        <th id="opcoes">Opções</th>
    </tr>
    </thead>

    <tbody>
    <?php if (!count($lista_pedidos)) : ?>
        <tr>
            <td colspan="6" class="sem-registros">Nenhum pedido encontrado.</td>
        </tr>
    <?php endif;

    /** @var Pedido $pedido */
    foreach ($lista_pedidos as $pedido) : ?>
        <tr>
            <td headers="pedido-id"><?php echo $pedido->getId() ?></td>
            <td headers="cliente">
                <?php echo $pedido->getNome() ?><br>
                <span class="lista-registros-comentario">
                    <?php echo $pedido->getEmail() ?>
                </span>
            </td>
            <td headers="itens" style="text-align: center"><?php echo count($pedido->getItens()) ?></td>
            <td headers="valor"><?php echo 'R$ ' . number_format($pedido->getValorTotal(), 2, ',', '') ?></td>
            <td headers="status">
                <span class="status-pedido -<?php echo strtolower($pedido->getStatus()) ?>">
                    <?php echo $pedido->getStatus() ?>
                </span>
            </td>
            <td headers="opcoes">
                <a href="/painel-dlx/apart-hotel/pedidos/detalhe?id=<?php echo $pedido->getId() ?>" class="link-detalhe" title="Detalhes do pedido">
                    Detalhe
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
[/CORPO]