<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Reservas\PainelDLX\Domain\Disponibilidade\Entities\Disponibilidade;
use Reservas\PainelDLX\Domain\Quartos\Entities\Quarto;
use Vilex\VileX;

/**
 * @var Vilex $this
 */

/** @var Quarto|null $quarto */
$quarto = $this->getAtributo('quarto');
?>

[CORPO]
<?php if ($quarto instanceof Quarto) : ?>
    <p class="form-paragr">
        <label for="num-qtde" class="form-rotulo">Qtde:</label>
        <input type="number" name="qtde" id="num-qtde" value="<?php echo $quarto->getQtde() ?>" min="0" max="<?php echo $quarto->getQtde() ?>" class="form-controle form-controle-numero" required>
    </p>

    <?php for ($i = 1; $i <= $quarto->getMaxHospedes(); $i++) : ?>
        <p class="form-paragr">
            <label for="num-valor-<?php echo $i ?>" class="form-rotulo form-controle-moeda">
                Valor (<?php echo $i ===  1 ? '1 pessoa' : "{$i} pessoas" ?>):
            </label>
            <input type="number" name="valores[<?php echo $i ?>]" id="num-valor-<?php echo $i ?>" value="<?php echo $quarto->getValorMin() ?>" min="<?php echo $quarto->getValorMin() ?>" max="9999.99" step="0.01" class="form-controle form-controle-numero" required>
        </p>
    <?php endfor; ?>
<?php else : ?>
    <p class="sem-registros">Quarto não encontrado.</p>
<?php endif; ?>
[/CORPO]