<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use DLX\Core\Configure;
use Reservas\Domain\Pedidos\Entities\Pedido;
use Reservas\Domain\Pedidos\Entities\PedidoItem;
use Vilex\VileX;

/**
 * @var VileX $this
 */

/** @var Pedido $pedido */
$pedido = $this->getAtributo('pedido');
$base_url = Configure::get('app', 'base-url');
?>

[CORPO]
<div style="margin: 30px 0">
    <p>
        Desculpe, mas seu pedido precisou ser cancelado!
        A cobrança do pedido não foi efetuado e as reservas não foram geradas ou já foram canceladas.
    </p>

    <p>
        Motivo informado: "<?php echo $this->getAtributo('motivo') ?>"
    </p>

    <p>
        Caso tenha interesse em alguma outra data ou quarto, clique
        <a href="<?php echo $base_url ?>nossos-quartos" target="_blank" rel="noopener" style="color: #E35243">aqui</a>
        e verifique outras opções.
    </p>
</div>


<div style="display: table; width: 100%;">
    <div style="float: left; width: 50%;">
        <h2 style="padding: 0; color: #75361a; font-size: 16px; text-transform: uppercase;font-weight: normal; margin: 0;">
            Resumo
        </h2>

        <p>
            <b>Nº do pedido:</b>
            #<?php echo $pedido->getId() ?>
        </p>

        <p>
            <b>Valor Total:</b>
            R$ <?php echo number_format($pedido->getValorTotal(), 2, ',', '') ?>
        </p>

        <p>
            <b>Status:</b>
            <?php echo $pedido->getStatus() ?>
        </p>
    </div>

    <div style="float: left; width: 50%;">
        <h2 style="padding: 0; color: #75361a; font-size: 16px; text-transform: uppercase;font-weight: normal; margin: 0;">
            Dados do hóspede
        </h2>

        <p>
            <b>Nome Completo:</b>
            <?php echo $pedido->getNome() ?>
        </p>

        <p>
            <b>CPF:</b>
            <?php echo $pedido->getCpf()->getCpfOculto() ?>
        </p>

        <p>
            <b>Email:</b>
            <?php echo $pedido->getEmail() ?>
        </p>

        <p>
            <b>Telefone:</b>
            <?php echo $pedido->getTelefone() ?>
        </p>
    </div>
</div>

<div style="margin-top: 20px">
    <h2 style="padding: 0; color: #75361a; font-size: 16px; text-transform: uppercase;font-weight: normal; margin: 0;">
        Reservas Solicitadas
    </h2>

    <table style="width: 100%; margin-top: 20px; border-collapse: collapse; font: 13px sans-serif">
        <thead style="border-bottom: 1px solid #efefef">
        <tr style="text-align: left">
            <th id="quarto">Quarto</th>
            <th id="checkin">Checkin</th>
            <th id="checkout">Checkout</th>
            <th id="qtde">Hóspedes</th>
            <th id="valor" style="text-align: right">Valor</th>
        </tr>
        </thead>

        <tbody>
        <?php
        /** @var PedidoItem $item */
        foreach ($pedido->getItens() as $item) : ?>
        <tr style="border-bottom: 1px solid #efefef;">
            <td headers="quarto" style="padding: 10px 0"><?php echo $item->getQuarto() ?></td>
            <td headers="checkin"><?php echo $item->getCheckin()->format('d/m/Y') ?></td>
            <td headers="checkout"><?php echo $item->getCheckout()->format('d/m/Y') ?></td>
            <td headers="qtde">
                <?php printf('%d adultos, %d crianças', $item->getQuantidadeAdultos(), $item->getQuantidadeCriancas()) ?>
            </td>
            <td headers="valor" style="text-align: right">
                <?php echo 'R$ ' . number_format($item->getValorTotal(), 2, ',', '') ?>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
[/CORPO]
