<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Reservas\Domain\Pedidos\Entities\Pedido;
use Reservas\Domain\Reservas\Entities\Reserva;
use Vilex\VileX;

/**
 * @var VileX $this
 */

/** @var Pedido $pedido */
$pedido = $this->getAtributo('pedido');
?>

[CORPO]
<div style="display: table; width: 100%">
    <div style="float: left; width: 50%">
        <h2 style="padding: 0; color: #75361a; font-size: 16px; text-transform: uppercase;font-weight: normal; margin: 0;">
            Resumo
        </h2>

        <p>
            <b>Nº do pedido:</b>
            #<?php echo $pedido->getId() ?>
        </p>

        <p>
            <b>Valor Total:</b>
            R$ <?php echo number_format($pedido->getValorTotal(), 2, ',', '') ?>
        </p>

        <p>
            <b>Status:</b>
            <?php echo $pedido->getStatus() ?>
        </p>
    </div>

    <div style="float: left; width: 50%;">
        <h2 style="padding: 0; color: #75361a; font-size: 16px; text-transform: uppercase;font-weight: normal; margin: 0;">
            Dados do hóspede
        </h2>

        <p>
            <b>Nome Completo:</b>
            <?php echo $pedido->getNome() ?>
        </p>

        <p>
            <b>CPF:</b>
            <?php echo $pedido->getCpf()->getCpfOculto() ?>
        </p>

        <p>
            <b>Email:</b>
            <?php echo $pedido->getEmail() ?>
        </p>

        <p>
            <b>Telefone:</b>
            <?php echo $pedido->getTelefone() ?>
        </p>
    </div>
</div>

<div style="margin-top: 20px">
    <h2 style="padding: 0; color: #75361a; font-size: 16px; text-transform: uppercase;font-weight: normal; margin: 0;">
        Suas Reservas
    </h2>

    <table style="width: 100%; margin-top: 20px; border-collapse: collapse; font: 13px sans-serif">
        <thead style="border-bottom: 1px solid #efefef">
        <tr style="text-align: left">
            <th id="id" style="text-align: center; width: 5%; padding: 8px 0">#</th>
            <th id="quarto">Quarto</th>
            <th id="checkin">Checkin</th>
            <th id="checkout">Checkout</th>
            <th id="qtde">Hóspedes</th>
            <th id="status">Status</th>
            <th id="valor" style="text-align: right">Valor</th>
        </tr>
        </thead>

        <tbody>
        <?php
        /** @var Reserva $reserva */
        foreach ($pedido->getReservas() as $reserva) : ?>
        <tr style="border-bottom: 1px solid #efefef;">
            <td headers="id" style="text-align: center; padding: 10px 0"><?php echo $reserva->getId() ?></td>
            <td headers="quarto"><?php echo $reserva->getQuarto() ?></td>
            <td headers="checkin"><?php echo $reserva->getCheckin()->format('d/m/Y') ?></td>
            <td headers="checkout"><?php echo $reserva->getCheckout()->format('d/m/Y') ?></td>
            <td headers="qtde">
                <?php printf('%d adultos, %d crianças', $reserva->getQuantidadeAdultos(), $reserva->getQuantidadeCriancas()) ?>
            </td>
            <td headers="status"><?php echo $reserva->getStatus() ?></td>
            <td headers="valor" style="text-align: right">
                <?php echo 'R$ ' . number_format($reserva->getValor(), 2, ',', '') ?>
            </td>
        </tr>
        <?php endforeach; ?>
        </tbody>

        <tfoot>
        <tr style="font-size: 15px;text-transform: uppercase; color: green">
            <td colspan="6" style="text-align: right; padding: 10px 0">Valor Total:</td>
            <td style="text-align: right"><?php echo 'R$ ' . number_format($pedido->getValorTotal(), 2, ',', '') ?></td>
        </tr>
        </tfoot>
    </table>
</div>
[/CORPO]
