version: '3.7'
services:
    reservas.dlx.com.br:
        container_name: br.com.dlx.reservas
        build:
            context: .
        volumes:
            - "/Volumes/Arquivos/Pessoal/dlepera/ProjetosWeb/painel-dlx/reservas-dlx/:/var/www/html/reservas.dlx.com.br"
        ports:
            - "8082:80"
        restart: always
        environment:
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: "
                client_host=host.docker.internal
                start_with_request=yes
            "
        networks:
            - bd
            - dlx
networks:
    bd:
        external: true
    dlx: {}