<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Reservas\PainelDLX\Domain\Entities\Quarto;
use Vilex\VileX;

/**
 * @var VileX $this
 */

$lista_reservas = $this->getAtributo('lista-quartos');
$filtro = $this->getAtributo('filtro');
?>
[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<nav class="menu-opcoes">
    <form id="filtro-registros" class="filtro-registros">
        <div class="multi-select">
            <span class="multi-select-item">Procurar em...</span>

            <div class="multi-select-itens">
                <label class="multi-select-item">
                    <input type="checkbox" name="campos[]" value="nome"<?php echo empty($filtro['campos']) || in_array('nome', $filtro['campos']) ? ' checked' : '' ?>>
                    Nome
                </label>

                <label class="multi-select-item">
                    <input type="checkbox" name="campos[]" value="link"<?php echo empty($filtro['campos']) || in_array('link', $filtro['campos']) ? ' checked' : '' ?>>
                    Link
                </label>

                <label class="multi-select-item">
                    <input type="checkbox" name="campos[]" value="max_hospedes"<?php echo empty($filtro['campos']) || in_array('max_hospedes', $filtro['campos']) ? ' checked' : '' ?>>
                    Máx. Hóspedes
                </label>

                <label class="multi-select-item">
                    <input type="checkbox" name="campos[]" value="valor_min"<?php echo empty($filtro['campos']) || in_array('valor_min', $filtro['campos']) ? ' checked' : '' ?>>
                    Valor Min.
                </label>
            </div>
        </div>

        <input type="search" name="busca" value="<?php echo $filtro['busca'] ?>" placeholder="Encontrar quartos" class="form-controle">
    </form>

    <button type="submit" form="filtro-registros" class="botao-buscar">Buscar</button>
    <a href="/painel-dlx/apart-hotel/quartos/novo" class="link-inserir">Adicionar quarto</a>
</nav>

<table id="lista-quartos" class="lista-registros">
    <thead>
    <tr>
        <th id="quarto-id">ID</th>
        <th id="nome">Nome</th>
        <th id="qtde" style="text-align: center;">Qtde.</th>
        <th id="max-hospedes" style="text-align: center;">Máx. Hóspedes</th>
        <th id="valor-min">Valor Min.</th>
        <th id="opcoes">Opções</th>
    </tr>
    </thead>

    <tbody>
    <?php if (!count($lista_reservas)) : ?>
        <tr>
            <td colspan="6" class="sem-registros">Nenhum quarto encontrado.</td>
        </tr>
    <?php endif;

    /** @var Quarto $quarto */
    foreach ($lista_reservas as $quarto) : ?>
        <tr>
            <td headers="quarto-id"><?php echo $quarto->getId() ?></td>
            <td headers="noem">
                <?php echo $quarto->getNome() ?><br>
                <span class="lista-registros-comentario"><?php echo $quarto->getLink() ?></span>
            </td>
            <td headers="qtde" style="text-align: center;"><?php echo $quarto->getQtde() ?></td>
            <td headers="max-hospedes" style="text-align: center;"><?php echo $quarto->getMaxHospedes() ?></td>
            <td headers="valor-min">
                R$ <?php echo number_format($quarto->getValorMin(), 2, ',', '') ?>
            </td>
            <td headers="opcoes">
                <a href="/painel-dlx/apart-hotel/quartos/detalhe?id=<?php echo $quarto->getId() ?>" class="link-detalhe" title="Informações desse quarto">
                    Detalhe
                </a>

                <a href="/painel-dlx/apart-hotel/quartos/editar?id=<?php echo $quarto->getId() ?>" class="link-editar" title="Editar esse quarto">
                    Editar
                </a>

                <a href="javascript:" class="link-excluir" onclick="excluirQuarto(<?php echo $quarto->getId() ?>)" title="Excluir esse quarto">
                    Excluir
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
[/CORPO]