<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Reservas\Domain\Quartos\Entities\Quarto;
use Vilex\VileX;

/**
 * @var Vilex $this
 */

/** @var Quarto $quarto */
$quarto = $this->getAtributo('quarto');
?>

[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<form id="form-upload" action="/painel-dlx/apart-hotel/quartos/upload-midias" method="post" enctype="multipart/form-data">
    <div class="upload-arquivos">
        <label class="upload-arquivos-campo">
            <span class="upload-arquivos-label">Selecione ou arraste os arquivos para cá</span>
            <input type="file" name="midias[]" accept="video/*,image/*" multiple required>
        </label>

        <div class="upload-arquivos-preview">

        </div>
    </div>

    <p class="form-botoes">
        <button type="submit" class="botao-upload" data-ajax-msg="Fazendo upload das mídias.<br>Por favor aguarde...">
            Iniciar Upload
        </button>
    </p>
</form>
[/CORPO]
