<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Reservas\Domain\Quartos\Contracts\QuartoMidiaCollectionInterface;
use Reservas\Domain\Quartos\Entities\Quarto;
use Reservas\Domain\Quartos\Entities\QuartoMidia;
use Vilex\VileX;

/**
 * @var Vilex $this
 */

if (!isset($quarto)) {
    /** @var Quarto $quarto */
    $quarto = $this->getAtributo('quarto');
}

/** @var QuartoMidiaCollectionInterface $lista_midias */
$lista_midias = $quarto->getMidias();

?>

<p class="mensagem-usuario -atencao">ATENÇÃO! Trecho em desenvolvimento!</p>

<?php if ($lista_midias->count() < 1) : ?>
    <p class="sem-registros">Nenhuma mídia encontrada.</p>
<?php else : ?>
    <div class="lista-midias-quarto">
        <?php
        /** @var QuartoMidia $midia */
        foreach ($lista_midias as $midia) : ?>
            <div class="midia-quarto">
                <?php echo $midia->getTagHtml() ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
