<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use PainelDLX\Domain\Usuarios\Entities\Usuario;
use Reservas\Domain\Pedidos\Entities\Pedido;
use Reservas\Domain\Pedidos\Entities\PedidoHistorico;
use Reservas\Domain\Pedidos\Entities\PedidoItem;
use Vilex\Templates\AbstractTemplate;

/**
 * @var AbstractTemplate $this
 */

/** @var Pedido $pedido */
$pedido = $this->getAtributo('pedido');

/** @var Usuario $usuario_logado */
$usuario_logado = $this->getAtributo('usuario-logado');

// @todo: retirar o style dessa página e passar para o arquivo CSS do ui-painel-dlx-reservas
?>

[HTML-HEAD]
<style>
    #link-detalhamento-periodo::before {
        color: orange;
    }
</style>
[/HTML-HEAD]

[CORPO]
<h1 class="titulo-pagina">{{ titulo-pagina }}</h1>

<div class="layout-barra-lateral">
    <aside class="barra-lateral">
        <div class="info-reserva">
            <div class="info-reserva-linha">
                <p class="info-reserva-dado">
                    <span class="info-reserva-rotulo">Pedido:</span>
                    # <?php echo $pedido->getId() ?>
                </p>
            </div>

            <div class="info-reserva-linha">
                <p class="info-reserva-dado">
                    <span class="info-reserva-rotulo">Valor:</span>
                    R$ <?php echo number_format($pedido->getValorTotal(), 2, ',', '') ?>
                </p>

                <p class="info-reserva-dado">
                    <span class="info-reserva-rotulo">Gateway de Pgto:</span>
                    <?php echo $pedido->getFormaPagamento() ?>
                </p>
            </div>

            <?php if ($pedido->isPendente() && !is_null($pedido->getCartao())) : ?>
                <div class="info-reserva-linha">
                    <p class="info-reserva-dado">
                        <span class="info-reserva-rotulo">
                            Cartão de <?php echo $pedido->getCartao()->getTipo(true) ?>:
                        </span>
                        <?php echo $pedido->getCartao()->getNumeroCartao() ?>
                    </p>
                </div>

                <div class="info-reserva-linha">
                    <p class="info-reserva-dado">
                        <span class="info-reserva-rotulo">Dono Cartão:</span>
                        <?php echo $pedido->getCartao()->getDono() ?>
                    </p>

                    <p class="info-reserva-dado">
                        <span class="info-reserva-rotulo">Data de Expiração:</span>
                        <?php echo $pedido->getCartao()->getValidade() ?>
                    </p>
                </div>

                <div class="info-reserva-linha">
                    <p class="info-reserva-dado">
                        <span class="info-reserva-rotulo">Código Segurança:</span>
                        <?php echo $pedido->getCartao()->getCodigoSeguranca() ?>
                    </p>

                    <p class="info-reserva-dado">
                        <span class="info-reserva-rotulo">Parcelas:</span>
                        <?php echo "{$pedido->getCartao()->getParcelas()}x" ?>
                    </p>
                </div>

                <div class="info-reserva-linha">
                    <p class="info-reserva-dado">
                        <span class="info-reserva-rotulo">Tipo:</span>
                        <?php echo $pedido->getCartao()->getTipo(true) ?>
                    </p>
                </div>
            <?php endif; ?>

            <div class="info-reserva-linha">
                <p class="info-reserva-dado">
                    <span class="info-reserva-rotulo">Status:</span>
                    <span class="status-pedido -<?php echo strtolower($pedido->getStatus()) ?>">
                        <?php echo $pedido->getStatus() ?>
                    </span>
                </p>
            </div>

            <?php if ($pedido->isPendente() || $pedido->isPago()) : ?>
                <div class="info-reserva-linha">
                    <p class="info-reserva-dado info-reserva-botoes">
                        <?php if ($pedido->isPendente()) : ?>
                            <button type="button" onclick="popupConfirmarPedido('confirmar', <?php echo $pedido->getId() ?>)" class="botao-salvar">Confirmar</button>
                            ou
                        <?php endif; ?>

                        <button type="button" onclick="popupConfirmarPedido('cancelar', <?php echo $pedido->getId() ?>)" class="botao-cancelar">Cancelar</button>
                    </p>
                </div>
            <?php endif; ?>
        </div>
    </aside>

    <div id="detalhe-pedido">
        <details class="detalhe-registro" open>
            <summary class="detalhe-registro-titulo">Hóspede / Cliente</summary>

            <p class="detalhe-registro-paragr">
                <span class="detalhe-registro-rotulo">Nome:</span>
                <?php echo $pedido->getNome() ?>
            </p>

            <p class="detalhe-registro-paragr">
                <span class="detalhe-registro-rotulo">CPF:</span>
                <span id="cpf-cliente">
                    <?php echo $pedido->isPago() ? $pedido->getCpf()->getCpfOculto() : $pedido->getCpf()->getCpfMask() ?>
                </span>

                <?php if ($pedido->isPago()) :
                    /** @var PedidoItem $pedido_item */
                    $pedido_item = $pedido->getItens()->first();
                    $reserva = $pedido_item->getReserva();
                    if ($reserva->podeVisualizarCpfCompleto($usuario_logado)) : ?>
                        <br>
                        <button id="btn-cpf-completo" onclick="mostrarCpfCompletoPedido(<?php echo $pedido->getId() ?>)" class="botao-mostrar-oculto" data-ajax-msg="Identificando CPF do cliente.<br>Por favor aguarde...">
                            CPF completo
                        </button>
                    <?php endif;
                endif; ?>
            </p>

            <p class="detalhe-registro-paragr">
                <span class="detalhe-registro-rotulo">Telefone:</span>
                <?php echo $pedido->getTelefone() ?>
            </p>

            <p class="detalhe-registro-paragr">
                <span class="detalhe-registro-rotulo">Email:</span>
                <?php echo $pedido->getEmail() ?>
            </p>
        </details>

        <details class="detalhe-registro" open>
            <summary class="detalhe-registro-titulo">Histórico</summary>

            <?php
            /** @var PedidoHistorico $historico */
            foreach ($pedido->getHistorico() as $historico) : ?>
                <p class="detalhe-registro-paragr">
                    <?php echo $historico ?>
                </p>
            <?php endforeach; ?>
        </details>

        <details class="detalhe-registro" open>
            <summary class="detalhe-registro-titulo">Reservas</summary>

            <table id="lista-reservas" class="lista-registros">
                <thead>
                <tr>
                    <th id="reserva-id">ID</th>
                    <th id="quarto">Quarto</th>
                    <th id="hospede">Hóspede</th>
                    <th id="periodo">Período</th>
                    <th id="valor">Valor</th>

                    <?php if ($pedido->isPago()) : ?>
                        <th id="status">Status</th>
                        <th id="opcoes">Opções</th>
                    <?php endif; ?>
                </tr>
                </thead>

                <tbody>
                <?php if (!$pedido->hasItens()) : ?>
                    <tr>
                        <td colspan="<?php echo $pedido->isPago() ? 7 : 5 ?>" class="sem-registros">Nenhum item encontrado.</td>
                    </tr>
                <?php endif;

                /** @var PedidoItem $pedido_item */
                foreach ($pedido->getItens() as $pedido_item) : ?>
                    <tr>
                        <td headers="item-id"><?php echo $pedido->getId() ?></td>
                        <td headers="quarto"><?php echo $pedido_item->getQuarto()->getNome() ?></td>
                        <td headers="hospede">
                            <?php echo $pedido->getNome() ?><br>
                            <span class="lista-registros-comentario">
                                <?php printf('%d adultos, %d crianças', $pedido_item->getQuantidadeAdultos(), $pedido_item->getQuantidadeCriancas()) ?>
                            </span>
                        </td>
                        <td headers="periodo">
                            <?php echo 'De ', $pedido_item->getCheckin()->format('d/m/Y'),
                            ' até ', $pedido_item->getCheckout()->format('d/m/Y') ?>

                            <?php if ($pedido_item->hasDetalhamento()) : ?>
                                <a href="javascript:" onclick="popupDetalhamentoPeriodo(<?php echo $pedido_item->getId() ?>)"
                                   id="link-detalhamento-periodo"
                                   title="Detalhamento do período"
                                   class="com-icone icone-pergunta so-icone"
                                   data-ajax-msg="Consultando detalhamento do item...<br>Por favor, aguarde."
                                >
                                    Detalhamento
                                </a>
                            <?php endif; ?>
                        </td>
                        <td headers="valor">
                            R$ <?php echo number_format($pedido_item->getValorTotal(), 2, ',', '') ?>
                        </td>

                        <?php if ($pedido->isPago()) : ?>
                            <td headers="status">
                                <span class="status-reserva -<?php echo strtolower($pedido_item->getReserva()->getStatus()) ?>">
                                    <?php echo $pedido_item->getReserva()->getStatus() ?>
                                </span>
                            </td>
                            <td headers="opcoes">
                                <a href="/painel-dlx/apart-hotel/reservas/detalhe?id=<?php echo $pedido_item->getReserva()->getId() ?>" class="link-detalhe" title="Detalhes da reserva">
                                    Detalhe
                                </a>
                            </td>
                        <?php endif; ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </details>
    </div>
</div>

<div id="popup-confirmar-pedido" class="popup-modal" style="display: none;"></div>
<div id="popup-detalhamento-periodo" class="popup-modal" style="display: none;"></div>
[/CORPO]