<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Reservas\Domain\Pedidos\Entities\Pedido;
use Reservas\Domain\Pedidos\Entities\PedidoItem;
use Reservas\Domain\Pedidos\Entities\PedidoItemDetalhe;
use Vilex\VileX;

/**
 * @var VileX $this
 */

/** @var PedidoItem $pedido_item */
$pedido_item = $this->getAtributo('pedido-item');
?>
[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<table id="lista-pedido-item-detalhamento" class="lista-registros">
    <thead>
    <tr>
        <th id="data">Data</th>
        <th id="diaria" style="text-align: right;">Valor</th>
        <th id="desconto" style="text-align: right;">Desconto</th>
        <th id="diaria-com-desconto">Valor c/ Desconto</th>
    </tr>
    </thead>

    <tbody>
    <?php
    /** @var PedidoItemDetalhe $pedido_item_detalhe */
    foreach ($pedido_item->getDetalhamento() as $pedido_item_detalhe) : ?>
        <tr>
            <td headers="data"><?php echo $pedido_item_detalhe->getData()->format('d/m/Y') ?></td>
            <td headers="diaria" style="text-align: right;">
                <?php echo 'R$' . number_format($pedido_item_detalhe->getDiaria(), 2, ',', '') ?>
            </td>
            <td headers="desconto" style="text-align: right;"><?php echo $pedido_item_detalhe->getPercentDesconto() ?></td>
            <td headers="diaria-com-desconto">
                <?php echo 'R$ ' . number_format($pedido_item_detalhe->getDiariaComDesconto(), 2, ',', '') ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
[/CORPO]