<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Reservas\Domain\Pedidos\Entities\Pedido;
use Vilex\VileX;

/**
 * @var VileX $this
 */

/** @var Pedido|null $pedido */
$pedido = $this->getAtributo('pedido');
?>
[CORPO]
<h1 class="titulo-pagina"><?php echo $this->getAtributo('titulo-pagina') ?></h1>

<form id="form-cancelar-pedido" action="/painel-dlx/apart-hotel/pedidos/cancelar-pedido" method="post">
    <input type="hidden" name="id" value="<?php echo $pedido->getId() ?>">

    <p class="mensagem-usuario -atencao">
        ATENÇÃO! Essa ação não pode ser defeita.<br>
        <?php if ($pedido->hasReservas()) : ?>
            Ao cancelar um pedido, todas as reservas vinculadas a ele serão canceladas também.<br>
        <?php endif; ?>
        Deseja realmente cancelar esse pedido?
    </p>

    <p class="form-paragr">
        <label for="txt-motivo" class="form-rotulo">Motivo:</label>
        <textarea name="motivo" id="txt-motivo" class="form-controle form-controle-textarea" required></textarea>
    </p>

    <p class="form-botoes">
        <button type="button" onclick="fecharPopupConfirmarPedido()" class="botao-salvar">Não quero cancelar o pedido</button>
        <button type="submit" class="botao-cancelar" data-ajax-msg="Cancelando esse pedido.<br>Por favor aguarde...">
            Sim, desejo cancelar esse pedido
        </button>
    </p>
</form>
[/CORPO]