<?php
/**
 * MIT License
 *
 * Copyright (c) 2018 PHP DLX
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

use Vilex\VileX;

/** @var $this Vilex */

$status = $this->getAtributo('status');
$qtde_pedidos = $this->getAtributo('quantidade-pedidos');
$cor = '-sucesso';

if ($qtde_pedidos > 0) {
    $cor = '-atencao';
}

if ($qtde_pedidos > 5) {
    $cor = '-erro';
}
?>

[CORPO]
<p class="qtde-pedidos-status <?php echo "-{$status} ", $cor ?>">
    <?php echo $qtde_pedidos, '<br>', $status ?>
    <br>
    <a href="/painel-dlx/apart-hotel/pedidos-<?php echo $status ?>" class="botao-salvar">Ver todos</a>
</p>
[/CORPO]
